### PR TITLE
Refactor sli

### PR DESCRIPTION
**Pull request by pnrobinson**
Hi Guys,
I added some code to do two things
1. Add fields for NCIT and Cellosaurus
2. Add functions to allow multiple SLI entries for some gene pair A and B, but to mark the one with the maximum activity as "maximum".  This means we can easily output unique entries by going
```
unique_list = [item for item in original_list if item.is_maximum()]
```
but we have all of the original data to display in supplements or websites.

Can we touch bases if this is a good final format? If so, I would try to get all of the human SLIs finished in the next few weeks.
I did not touch the yeast code, and indeed it might need a different format because it does not have cancer type or cellosaurus? Is there a better way?

### CODE REVIEW

**Comment by justaddcoffee** [comment]
Looks good. 

> I did not touch the yeast code, and indeed it might need a different format because it does not have cancer type or cellosaurus? Is there a better way?

One way to handle this would be to add a `species_ID` to `SyntheticLethalInteraction` and then allow  `cell_line` `cellosaurus_id` and `cancer_type` to be `None`. Want me to do this and push?

**Comment by justaddcoffee** [comment]
> One way to handle this would be to add a species_ID to SyntheticLethalInteraction that defaults to 9606, and then allow cell_line cellosaurus_id and cancer_type to be None. Want me to do this and push?

I just did this ^^, and pushed to this branch. Please feel free to revert if this isn't what we want...

**Comment by pnrobinson** [comment]
a Species ID sounds like a useful addition! Are we ready to merge?

**Comment by justaddcoffee** [comment]
Yes, merge away

**Pull request merged**
