### PR TITLE
Parse Costanzo Boone et al 2016 synthetic lethal data from yeast

### PR DESCRIPTION
**Pull request by justaddcoffee**
To address #10 

Added method to download, parse, and output SL data from Constanzo et al.

Note that this method by default applies only a very lenient filter of p < 0.05. Downstream users can further filter by epsilon score, as suggested in Supplementary Data: 

> "The interaction data ... should be filtered prior to use. We suggest three different thresholds [lenient (P < 0.05), intermediate (P < 0.05 and e < 0.08), and stringent confidence (P <0.05 and e > 0.16 or e < -0.12)]"

### CODE REVIEW

**Comment by deepakunni3** [comment]
@justaddcoffee If you feel this is ready then feel free to merge 👍

**Comment by justaddcoffee** [comment]
@deepakunni3 can I have admin on this repo? Can't merge at the moment

**Comment by deepakunni3** [comment]
Thou hath been granted power!

You should have an invitation to the repo.

**Comment by justaddcoffee** [comment]
Thanks! And stop working during your vacation!

**Comment by deepakunni3** [comment]
Hey, I am working today 😼

**Pull request merged**
